// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfuuhpflmglnubkpuohl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdXVocGZsbWdsbnVia3B1b2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjM0NTQsImV4cCI6MjA2MTMzOTQ1NH0.H8C7xDdIR4ypI7so5Z8rZ43EvKXoQBa_9k9KmPWtXlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);